CREATE TABLE recipes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    category   VARCHAR(50)  NOT NULL,
    img_url    TEXT,
    servings   INT,
    prep_time  INT,
    cook_time  INT,
    notes      TEXT,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE ingredients
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT REFERENCES recipes (id) ON DELETE CASCADE,
    name      VARCHAR(255) NOT NULL,
    amount    DECIMAL      NOT NULL,
    unit      VARCHAR(50)  NOT NULL
);

CREATE TABLE instructions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id   BIGINT REFERENCES recipes (id) ON DELETE CASCADE,
    step_order  INT  NOT NULL,
    description TEXT NOT NULL
);